__author__ = 'nlsegerl'

import trustedanalytics as ta

ER_VISIT_COUNT = 'ER_VISIT_COUNT'
OUTPATIENT_VISIT_COUNT = 'OUTPATIENT_VISIT_COUNT'
HISTORICAL_INPAT_MEDLIST = 'HISTORICAL_INPAT_MEDLIST'
HISTORICAL_OUTPAT_MEDLIST = 'HISTORICAL_OUTPAT_MEDLIST'
